name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  job-test:
    name: Test
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Install codecov
        run: |
          apt-get update
          apt-get install -y libcap2-bin

      - name: Run test
        run: make ci

      - name: Run octocov
        uses: k1LoW/octocov-action@v0
